version: "3"
services:
  app:
    container_name: covid19
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
        - 3000:3000
    volumes:
        - .:/app
        - node_modules:/app/node_modules

  fetch_fukui_data:
    build: ./covid19_fukui
    volumes:
      - ./data:/app/data
      - ./covid19_fukui:/app/covid19_fukui
      - /app/covid19_fukui/node_modules

volumes:
  node_modules: {}
