[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[context.production]
  # https://stackoverflow.com/questions/3856747/check-whether-a-certain-file-type-extension-exists-in-directory
  # data ディレクトリの中に json ファイルが
  #   無ければ json ファイルを生成。 
  #   既に存在すれば何もしない。
  command = "if [ $(ls -1 data/*.json 2>/dev/null | wc -l) == 0 ]; then pushd covid19_fukui && yarn fetch && popd; fi && yarn generate:deploy"

[context.branch-deploy]
  command = "if [ $(ls -1 data/*.json 2>/dev/null | wc -l) == 0 ]; then pushd covid19_fukui && yarn fetch && popd; fi && yarn generate:dev"

[context.deploy-preview]
  command = "if [ $(ls -1 data/*.json 2>/dev/null | wc -l) == 0 ]; then pushd covid19_fukui && yarn fetch && popd; fi && yarn generate:dev"
